.github/workflows/ci.yml
* Build and upload pex file via GitHub actions
* Perform tests via GitHub actions
=> Add CI pipeline via GitHub actions

tests/unit/processor/datetime_extractor/test_date_time_extractor.py
* Fixed problems in the datetime extractor tests that can be caused daylight savings.
=> Fix problem in datetime extractor tests caused by daylight savings

doc/source/user_manual/configuration/processor.rst, doc/source/user_manual/introduction.rst, logprep/processor/selective_extractor/factory.py, logprep/processor/selective_extractor/processor.py, tests/acceptance/test_full_message_pass_with_hmac.py, tests/acceptance/test_selective_extractor_full_pipeline_pass.py, tests/acceptance/util.py, tests/testdata/acceptance/selective_extractor/extract.jsonl, tests/testdata/acceptance/selective_extractor/whitelist.txt, tests/unit/processor/list_comparison/test_list_comparison.py, tests/unit/processor/selective_extractor/test_selective_extractor.py
This commit adds the selective extraction enricher. It also contains some refactoring,
as well as the tests and documentation.
=> Add selective extraction processor

tests/unit/processor/base.py, tests/unit/processor/pseudonymizer/test_pseudonymizer.py
this is the first pull request of a bigger refactoring story to ensure, that all processors are able to accept and process generic and specific rules.
=> Dev create base class for processor tests

logprep/processor/datetime_extractor/factory.py, logprep/processor/datetime_extractor/processor.py, tests/testdata/unit/datetime_extractor/rules/datetime_extractor.json, tests/testdata/unit/datetime_extractor/rules/generic/datetime_extractor.json, tests/testdata/unit/datetime_extractor/rules/specific/datetime_extractor.json, tests/unit/processor/__init__.py, tests/unit/processor/base.py, tests/unit/processor/datetime_extractor/test_date_time_extractor.py
=> Dev refactor datetime_extractor to use BaseProcessorTestCase

logprep/processor/base/processor.py, logprep/processor/clusterer/factory.py, logprep/processor/clusterer/processor.py, logprep/processor/clusterer/rule.py, pyproject.toml, tests/testdata/unit/clusterer/rules/generic/rules.json, tests/testdata/unit/clusterer/rules/specific/rules.json, tests/unit/processor/base.py, tests/unit/processor/clusterer/test_clusterer.py, tests/unit/processor/test_processor_factory.py
part of story to implement a common interface for generic and specific rule supporting processors
=> Dev refactor clusterer tests to use base class

logprep/processor/template_replacer/factory.py, logprep/processor/template_replacer/processor.py, tests/testdata/unit/template_replacer/rules/generic/template_replacer.json, tests/testdata/unit/template_replacer/rules/specific/template_replacer.json, tests/testdata/unit/template_replacer/rules/template_replacer.json, tests/unit/processor/base.py, tests/unit/processor/template_replacer/test_template_replacer.py
Refactor template_replacer to support generic and specific rules
=> dev refactor template_replacer to use base class

doc/source/conf.py, doc/source/user_manual/configuration/processor.rst
Due to the many changes regarding the processor configuration
the rst documentation was not up to date. This pull requests
adjusts the configurations such that it is clear which processor
supports generic and specific rules, and which not.
=> Revise rst documentation for processor configs

.github/workflows/ci.yml, .github/workflows/main.yml, README.md, logprep/processor/generic_resolver/factory.py, logprep/processor/generic_resolver/processor.py, logprep/processor/geoip_enricher/factory.py, logprep/processor/list_comparison/processor.py, logprep/processor/list_comparison/rule.py, tests/acceptance/test_wineventlog_processing.py, tests/unit/processor/list_comparison/test_list_comparison.py, tests/unit/processor/list_comparison/test_list_comparison_rule.py
Add code quality checks to pipeline
If merged pipeline
- will fail on black formatting errors
- will fail if changed and newly added files won't reach pylint score of 9.5
- will fail if test coverage decreases (we will see if merged for main)
=> 58 pipeline should fail on code quality

logprep/processor/labeler/factory.py
=> Fix black for labeler factory

logprep/util/auto_rule_tester.py, tests/testdata/unit/auto_rule_tester/normalizer/regex_mapping.yml, tests/testdata/unit/auto_rule_tester/normalizer/rules/generic/auto_test_normalizer_match.json, tests/testdata/unit/auto_rule_tester/normalizer/rules/generic/auto_test_normalizer_match_test.json, tests/testdata/unit/auto_rule_tester/normalizer/rules/specific/auto_test_normalizer_match.json, tests/testdata/unit/auto_rule_tester/normalizer/rules/specific/auto_test_normalizer_match_test.json, tests/unit/util/test_auto_rule_tester.py
=> Fix auto tester without rules

.github/workflows/ci.yml, .github/workflows/main.yml, doc/source/user_manual/configuration/processor.rst, doc/source/user_manual/introduction.rst, logprep/processor/base/exceptions.py, logprep/processor/hyperscan_resolver/processor.py, logprep/processor/processor_factory.py, requirements.in, requirements.txt, requirements_dev.txt, tests/testdata/unit/processor_factory/test_broken_processor/factory.py, tests/testdata/unit/processor_factory/test_broken_processor/processor.py, tests/testdata/unit/processor_factory/test_processor/factory.py, tests/testdata/unit/processor_factory/test_processor/processor.py, tests/unit/processor/hyperscan_resolver/test_hyperscan_resolver.py, tests/unit/processor/hyperscan_resolver/test_hyperscan_resolver_rule.py, tests/unit/processor/test_processor_factory.py
Hyperscan >0.1.5 requires to install hyperscan libraries, but 0.1.5 does not seem run for python >3.8 despite what is said in the requirements.
Furthermore, it is compiled for x86_64 linux.
=> Downgrade hyperscan to 0.1.5 and install only for x86_64 linux

logprep/processor/base/processor.py, logprep/processor/pre_detector/ip_alerter.py, logprep/util/auto_rule_tester.py, tests/unit/processor/base.py, tests/unit/processor/pre_detector/test_ip_alerter.py, tests/unit/util/test_helper.py
=> Change get_dotted_field_value to check for dict type everywhere

README.md, doc/source/user_manual/dry_run.rst, doc/source/user_manual/index.rst, doc/source/user_manual/validation.rst, doc/source/user_manual/verification.rst, logprep/run_logprep.py, logprep/util/configuration.py, quickstart/exampledata/config/pipeline.yml, tests/unit/util/test_configuration.py
Solves #63 and adds dedicated verification option.
=> Limit config verification for auto-tests and rule validation

logprep/processor/list_comparison/factory.py, logprep/processor/list_comparison/processor.py, logprep/processor/list_comparison/rule.py, quickstart/exampledata/config/pipeline.yml, tests/testdata/unit/list_comparison/rules/generic/user_check.json, tests/testdata/unit/list_comparison/rules/specific/user_check_specific.json, tests/unit/processor/list_comparison/test_list_comparison.py, tests/unit/processor/list_comparison/test_list_comparison_rule.py
=> Fix list comparison base paths

.github/workflows/publish-latest-dev-release-to-pypi.yml, .github/workflows/publish-release-to-pypi.yml, README.md, doc/source/conf.py, doc/source/installation.rst, pyproject.toml, setup.py
Once this pull request is merged logprep will be published to pypi.
The workflow changes include an upload to pypi once a new release is 
made. If a pull request is merged into the main branch without a release 
then a Development Build is released on github. This Development Build
is based on the tag `latest` and will be overwritten with every new merge 
into main. The corresponding github workflow removes the old `latest `tag, sets a 
new one on the latest commit hash, removes the last Development Build
and creates a new one again. Resulting in a always up to date dev build
=> PyPi Upload Preparations

tox.ini
=> Add missing sphinxcontrib-mermaid dependency tox docs building

logprep/processor/clusterer/processor.py, tests/unit/processor/clusterer/test_clusterer.py
=> Ensure matching rules are cleared for clusterer on processing

doc/source/conf.py
fix the generation of documentation for readthedocs
=> fix readthedocs docs generation

.readthedocs.yaml, doc/requirements.txt
works now as expected:
https://logprep.readthedocs.io/en/fix-setup-rtd-log-generation/development/processor_how_to.html
=> Fix setup rtd log generation

logprep/processor/pseudonymizer/processor.py, tests/testdata/mock_external/tld_list.dat, tests/unit/processor/pseudonymizer/test_pseudonymizer.py
=> Fix tld variable in pseudonymizer

logprep/processor/list_comparison/processor.py, logprep/util/auto_rule_tester.py, tests/unit/util/test_auto_rule_tester.py
=> Handle processor specific rule initialization in auto tester

doc/source/development/processor_how_to.rst, logprep/processor/dropper/processor.py
This pull requests adds documentation about writing new 
processor specific metrics.
=> Extend documentation for new processor specific metrics

doc/source/user_manual/rule_language.rst
I added some documentation for the delete processor.
=> Add Documentation for delete processor

.vscode/settings.json
this hides some files in file explorer
=> add file excludes to vscode settings

logprep/input/dummy_input.py, logprep/input/input.py, logprep/input/json_input.py, logprep/input/jsonl_input.py, logprep/output/console_output.py, logprep/output/output.py, logprep/output/writing_output.py, tests/unit/connector/test_console_output.py, tests/unit/connector/test_dummy_input.py, tests/unit/connector/test_json_input.py, tests/unit/connector/test_jsonl_input.py, tests/unit/connector/test_writing_output.py
this prepares the connector code to be refactored and split in next steps
=> Increase Test Coverage for Connectors

logprep/abc/processor.py, logprep/connector/confluent_kafka_shared.py, logprep/input/confluent_kafka_input.py
This PR removes code never called within tests and never used somewhere
=> Remove unused code

.github/workflows/ci.yml, .readthedocs.yaml, doc/requirements.txt, doc/source/getting_started.rst
docs still failing because of missing pytest
=> 192 docs build is failing

logprep/util/configuration.py, tests/unit/util/test_configuration.py
If logprep was run with a config that didn't had an `input` or `output` key an error message like `missing connector key` was raised. This pull requests fixes this behavior.
=> Fix error message for missing input/output config keys

logprep/processor/field_manager/processor.py, tests/unit/processor/field_manager/test_field_manager.py
fixes the missing_fields output for error warning
=> Fix error message for processing error in field_manager

logprep/processor/domain_label_extractor/processor.py, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py
* this fixes a bug if the source_field does not exist
* removes unused exception
* refactors loop over labels_dict
=> fix bug for non existing source_field in domain_label_extractor

logprep/processor/base/rule.py, tests/testdata/unit/domain_resolver/rules/generic/domain_resolver.yml
* this helps on debugging because you are able to see the rule config in debugger as repr
=> add new representation for rules

logprep/util/aggregating_logger.py, logprep/util/log_aggregator.py, tests/unit/util/test_log_aggregator.py
* reimplemented using a mock of time.time
* removed unused code
* increased test coverage
=> Reimplement flipping aggregation test

CHANGELOG.md, doc/source/user_manual/configuration/processor.rst, doc/source/user_manual/configuration/rules.rst, logprep/processor/calculator/fourFn.py, logprep/processor/calculator/processor.py, logprep/processor/calculator/rule.py, logprep/registry.py, logprep/util/decorators.py, logprep/util/getter.py, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt, tests/testdata/unit/calculator/generic_rules/calculator.json, tests/testdata/unit/calculator/specific_rules/calculator.json, tests/unit/processor/calculator/test_calculator.py, tests/unit/processor/calculator/test_calculator_rule.py
* add a processor that is able to calculate with field values
=> Add calculator processor

requirements.in, requirements.txt, requirements_dev.txt
* is needed because they revoked a root certificate
=> upgrade certifi

logprep/abc/processor.py, logprep/processor/list_comparison/processor.py, tests/unit/processor/base.py
* removes dir validation from rules
* removes file validation from list comparision
=> fix http config load - remove hard filesystem validations

doc/source/development/notebooks/processor_examples/timestamp_differ.ipynb, logprep/processor/timestamp_differ/processor.py, logprep/processor/timestamp_differ/rule.py, tests/unit/processor/timestamp_differ/test_timestamp_differ.py
- Can be shown by setting a new config field
=> Hide units by default

README.md, logprep/abc/getter.py, logprep/connector/confluent_kafka/input.py, logprep/run_logprep.py, logprep/util/configuration.py, logprep/util/getter.py, quickstart/exampledata/config/pipeline.yml, tests/testdata/config/config-docker.yml, tests/testdata/config/config.yml, tests/testdata/config/config2.yml, tests/unit/test_run_logprep.py, tests/unit/util/test_getter.py
* version output could potentially expose secret data
=> fix version output

logprep/util/getter.py, tests/unit/test_runner.py, tests/unit/util/test_getter.py
* in networks bad things could happen easily 
* this should make thinks a litte bit more robust
=> make http getter more robust

CHANGELOG.md, logprep/abc/getter.py, quickstart/exampledata/config/pipeline.yml, tests/unit/util/test_getter.py
* this adds the functionality to use environment variables in rules and config (pipeline.yml)
=> Dev substitute from environment in config and rules

CHANGELOG.md, logprep/processor/dissector/processor.py, logprep/processor/dissector/rule.py, logprep/util/helper.py, tests/unit/processor/dissector/test_dissector.py, tests/unit/processor/dissector/test_dissector_rule.py
=> add append without separator to dissector

Dockerfile, quickstart/Dockerfile, quickstart/docker-compose.yml
=> Revert "fix quickstart docker-compose setup"

CHANGELOG.md, logprep/processor/base/rule.py, logprep/util/helper.py, tests/unit/processor/requester/test_requester.py, tests/unit/util/test_helper.py
* this adds simple list access to `get_dotted_field_value` helper function
* slicing is not supportet yet
=> add list access to get_dotted_field_value

CHANGELOG.md, doc/source/development/processor_how_to.rst, logprep/util/processor_generator.py, logprep/util/template_processor.py.j2, logprep/util/template_processor_test.py.j2, logprep/util/template_rule.py.j2, logprep/util/template_rule_test.py.j2, requirements_dev.in, requirements_dev.txt, tests/unit/util/test_processor_generator.py
This adds a little helper for generating code to implement new processors.
=> add processor boilerplate generator helper

logprep/processor/dissector/rule.py, tests/unit/processor/dissector/test_dissector.py, tests/unit/processor/dissector/test_dissector_rule.py
=> fix dissector regex

logprep/processor/domain_resolver/rule.py, tests/acceptance/test_full_configuration.py, tests/acceptance/util.py
* fixes a type hint for target_field
* renames TestHTTPServer to get rid of pytest warning
=> fix type hint for target_field

CHANGELOG.md, logprep/processor/dissector/rule.py, tests/unit/processor/dissector/test_dissector.py, tests/unit/processor/dissector/test_dissector_rule.py
* adds datatype conversion shorthand syntax to dissect pattern language
* adds bool datatype conversion that translates to bool by meaning
=> Add shorthand to dissect pattern for converting datatypes

CHANGELOG.md
=> update changelog bump `attrs` requirement

CHANGELOG.md, doc/source/user_manual/configuration/configurationdata.rst, logprep/abc/getter.py, logprep/run_logprep.py, logprep/util/configuration.py, tests/acceptance/test_full_configuration.py, tests/acceptance/test_http_input.py, tests/acceptance/util.py, tests/unit/util/test_configuration.py, tests/unit/util/test_getter.py
=> fix handle template errors

CHANGELOG.md, logprep/abc/connector.py, logprep/framework/pipeline.py, logprep/metrics/metric_exposer.py, tests/acceptance/test_full_configuration.py, tests/acceptance/util.py, tests/unit/framework/test_pipeline.py, tests/unit/metrics/test_metric_exposer.py, tests/unit/metrics/test_metric_targets.py
This pull-request fixes a metrics bug when multiple outputs are configured.
TODOs:
closes #335
=> Fix metrics for multiple outputs

logprep/abc/processor.py, logprep/processor/base/exceptions.py, logprep/processor/domain_label_extractor/processor.py, logprep/processor/field_manager/processor.py, logprep/processor/generic_adder/processor.py, logprep/processor/generic_resolver/processor.py, logprep/processor/geoip_enricher/processor.py, logprep/processor/hyperscan_resolver/processor.py, logprep/processor/list_comparison/processor.py, logprep/processor/normalizer/processor.py, logprep/processor/requester/processor.py, logprep/processor/string_splitter/processor.py, logprep/processor/template_replacer/processor.py, logprep/processor/timestamp_differ/processor.py, tests/unit/exceptions/processor/test_processing_warning.py, tests/unit/processor/amides/test_amides.py, tests/unit/processor/concatenator/test_concatenator.py, tests/unit/processor/datetime_extractor/test_datetime_extractor.py, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py, tests/unit/processor/domain_resolver/test_domain_resolver.py, tests/unit/processor/field_manager/test_field_manager.py, tests/unit/processor/key_checker/test_key_checker.py, tests/unit/processor/list_comparison/test_list_comparison.py, tests/unit/processor/normalizer/test_normalizer.py, tests/unit/processor/template_replacer/test_template_replacer.py
Add spacing between skipped fields in FieldExistsWarning and fix typo in same error
=> Improve error message

logprep/util/time_measurement.py, tests/unit/processor/base.py, tests/unit/util/test_time_measurement.py
the test also checks now for an actual deleter implementation
closes #434
=> time measurement checks for caller class name now

.github/workflows/main.yml
this is from #445 
we forgot this.
=> fix main pipeline

CHANGELOG.md, README.md, logprep/run_logprep.py, logprep/util/getter.py, quickstart/docker-compose.yml, quickstart/exampledata/config/nginx/conf.d/.htpasswd, quickstart/exampledata/config/nginx/conf.d/default.conf, quickstart/exampledata/config/nginx/nginx.conf, quickstart/exampledata/config/postgresql/keycloak_db.sql, tests/unit/test_run_logprep.py, tests/unit/util/test_getter.py
this removes url string auth injection to ensure it is not leaked via logs. additionally this prepares oauth flow token renewal
=> remove url string credential injection

CHANGELOG.md, logprep/connector/opensearch/output.py, tests/unit/connector/test_opensearch_output.py
performance improvement: https://github.com/fkie-cad/Logprep/wiki/opensearch-parallel-bulk
=> use opensearch parallel bulk

CHANGELOG.md, logprep/util/configuration.py, logprep/util/helper.py, tests/unit/test_quickstart.py, tests/unit/util/test_configuration.py
=> Fix versioneer and PROMETHEUS_MULTIPROC_DIR bug

tests/acceptance/test_http_input.py
removed the tests, because they are currently testing only a POC, but failing in CI pipeline which is very annoying
closes #519
=> remove multiple pipeline tests for http_input

.readthedocs.yaml, doc/source/development/coding_examples.rst
=> fix documentation examples

.vscode/extensions.json, CHANGELOG.md, doc/source/user_manual/execution.rst, logprep/framework/pipeline_manager.py, logprep/run_logprep.py, logprep/runner.py, logprep/util/configuration.py, logprep/util/defaults.py, tests/acceptance/test_amides.py, tests/acceptance/util.py, tests/unit/framework/test_pipeline_manager.py, tests/unit/test_run_logprep.py, tests/unit/test_runner.py
=> revise restart behavior

CHANGELOG.md, logprep/util/configuration.py, tests/unit/util/test_configuration.py
=> configuration overwrites with default values

charts/logprep/Chart.yaml, charts/logprep/templates/deployment.yaml, charts/logprep/values.yaml, tests/unit/charts/test_deployment.py
populate volumes and mounts from value keys
adds logprep-cache-dir in memory volume and mounts it to /home/logprep/.cache
=> add support for extraVolumes and extraMounts

examples/k8s/Chart.yaml
this generalizes the chart version in the example to always install the latest version
=> generalize chart version

CHANGELOG.md, logprep/abc/processor.py
add an experimental option to bypass the rule tree during processing
=> option to  bypass rule tree

.readthedocs.yaml
currently it is broken because of missing rust. this tries to fix this.
=> Fix automatic docs generation

examples/exampledata/config/pipeline.yml, logprep/abc/processor.py, logprep/connector/confluent_kafka/input.py, logprep/connector/confluent_kafka/output.py, logprep/framework/pipeline.py, tests/unit/connector/test_confluent_kafka_input.py, tests/unit/connector/test_confluent_kafka_output.py
=> add minor improvements

.pre-commit-config.yaml, CHANGELOG.md, CONTRIBUTING.md, pyproject.toml
- Introduced `pre-commit` hooks for code quality and consistency.
- Updated `CHANGELOG.md` and `CONTRIBUTING.md` for new setup instructions.
- Added `pre-commit` to dev dependencies in `pyproject.toml`.
=> add pre-commit hooks and update documentation

CHANGELOG.md, logprep/processor/timestamp_differ/rule.py
=> Fix timestamp differ rule doc

.dockerignore, .github/workflows/container-build.yml, CHANGELOG.md, Dockerfile
* adds qemu setup action
* adds buildx seetup action
* adds platforms to builds
=> add multiarch container build

CHANGELOG.md, logprep/filter/lucene_filter.py, tests/unit/filter/test_lucene_filter.py
This PR fixes a conflict between the Crypto module and the lucene filter.
=> Fix bug lucene lex

CHANGELOG.md, Dockerfile
* uninstall pypa setuptools from image
* use slim image for production
* this fixes the pipeline
=> use official python image

.github/workflows/main.yml
this only applies changes from ci pipeline to main pipeline. 
we should refactor it in the future in #762
=> fix lint job for main pipeline

logprep/generator/http/loader.py, tests/unit/generator/http/test_batcher.py, tests/unit/generator/http/test_loader.py, tests/unit/generator/http/test_sender.py
Fixed outdated tests in batcher, loader, sender, buffer
=> fixed old tests in batcher, sender, loader, buffer

tests/unit/util/test_configuration.py
=> fix broken configuration test

CHANGELOG.md, logprep/ng/abc/event_metadata.py, logprep/ng/inputs/kafka_input.py, tests/unit/ng/inputs/test_kafka_input.py
*add abstract event metadata class
*update CHANGELOG.md
*implement concrete kafka metaclass
*add unittests for kafka metaclass
=> Dev eventmetadata class implementation

CHANGELOG.md, logprep/ng/event.py, logprep/ng/event_state.py, tests/unit/ng/test_event_state.py, tests/unit/ng/test_events.py
* implement EventState class to manage the lifecycle of log events
* integrate a finite state machine to control valid state transitions
* support for both automatic and conditional (success-based) state transitions
=> Dev eventstate implementation

doc/source/development/notebooks/new_architecture_examples/1_event_metadata.ipynb, doc/source/development/notebooks/new_architecture_examples/2_event_state.ipynb, doc/source/development/notebooks/new_architecture_examples/3_event_class.ipynb, doc/source/development/notebooks/new_architecture_examples/4_further_event_classes.ipynb, doc/source/development/notebooks/new_architecture_examples/5_event_backlog.ipynb, tests/unit/ng/connector/confluent_kafka/test_metadata.py
Jupyter Notebook demonstrations for implemented classes (new architecture)
=> Review sprint52

CHANGELOG.md, logprep/run_logprep.py, logprep/util/context_managers.py, tests/unit/processor/domain_resolver/test_domain_resolver.py, tests/unit/test_run_logprep.py, tests/unit/util/test_auto_rule_tester.py, tests/unit/util/test_context_managers.py
* Fix stuck auto-rule tester
* Fix failing domain resolver tests
=> Fix auto-rule tester getting stuck due to logging
