fkie-cad/Logprep

doc/source/user_manual/rule_language.rst, logprep/processor/domain_resolver/processor.py, logprep/processor/domain_resolver/rule.py, logprep/processor/geoip_enricher/processor.py, logprep/processor/geoip_enricher/rule.py, logprep/util/helper.py, tests/testdata/unit/domain_resolver/rules/domain_resolver.json, tests/testdata/unit/geoip_enricher/rules/geoip_all.json, tests/unit/processor/domain_resolver/test_domain_resolver.py, tests/unit/processor/geoip_enricher/test_geoip_enricher.py
Modified the geoip_enricher and domain_resolver to allow for configurable output fields (per rule basis).
Both still use the default output fields as default values in case none is provided. 
Also modified unit tests accordingly and extended the documentation.
=> Dev configurable output fields geoip and domain resolver

doc/source/user_manual/rule_language.rst, logprep/processor/normalizer/processor.py, tests/unit/processor/normalizer/test_normalizer.py
This pull request implements a unix source format feature for the timestamp normalization. With this it is possible to use 'UNIX' in a normalization rule to normalize a unix epoch timestamp. This works with seconds and milliseconds.
=> add unix source format for timestamp normalization

doc/source/user_manual/configuration/processor.rst, doc/source/user_manual/introduction.rst, doc/source/user_manual/rule_language.rst, logprep/processor/base/processor.py, logprep/processor/domain_label_extractor/factory.py, logprep/processor/domain_label_extractor/processor.py, logprep/processor/domain_label_extractor/rule.py, tests/testdata/unit/domain_label_extractor/rules/domain_label_extractor.json, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py
This processor allows to split a given domain into it's parts/labels. Additionally this commit pushes a change to the field_exists method in the base processor. This is to prevent indexing a string with a field value.
=> add a new domain label extractor processor

logprep/util/auto_rule_tester.py
This allows to get an overview of how many rules have unit tests.
=> Add calculate rule test coverage to auto rule tester

doc/source/user_manual/configuration/connector.rst, logprep/connector/confluent_kafka.py, logprep/util/helper.py, tests/acceptance/test_full_message_pass_with_hmac.py, tests/unit/connector/test_confluent_kafka.py, tests/unit/util/test_helper_add_field.py
This modification to the confluent kafka connector allows to verify the integrity of an incoming message
=> Add a hmac to an incoming event from kafka

doc/source/user_manual/rule_language.rst, logprep/processor/geoip_enricher/processor.py, tests/testdata/unit/geoip_enricher/rules/geoip_all.json, tests/unit/processor/geoip_enricher/test_geoip_enricher.py
This allows to save the geoip data in custom subfields, depending on the configured dotted output field.
=> Add dotted output fields for the geoip enricher processor

logprep/run_logprep.py, logprep/util/auto_rule_tester.py, logprep/util/helper.py, logprep/util/json_handling.py, logprep/util/rule_dry_runner.py, tests/acceptance/test_full_message_pass_with_hmac.py, tests/acceptance/test_pre_detection.py, tests/acceptance/test_selective_extractor_full_pipeline_pass.py, tests/acceptance/test_wineventlog_normalization.py, tests/acceptance/test_wineventlog_processing.py, tests/acceptance/test_wineventlog_pseudonymization.py, tests/acceptance/util.py
Some test util functions where moved to logprep source util. This
prevents the need of development libraries such as 'pytest' to be
imported in production. Previously when logprep was called with the
argument --validate-rules test code was imported, this is not the case
anymore.
=> Refactor code to decouple source code from test code

logprep/util/processor_stats.py
As the selective extractor is not configured via rules there are also
no statistics of matched rules in the processor stats. Previously
this was not considered and a KeyError was the result. Now to 
account for this the processor stats module ignores the 
'matches_per_idx' and 'times_per_idx' stats for the selective 
extractor processor.
=> Fix selective extractor stats

doc/source/user_manual/configuration/processor.rst, doc/source/user_manual/introduction.rst, logprep/processor/domain_label_extractor/factory.py, logprep/processor/domain_label_extractor/processor.py, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py
The unrecognized domain label error has been removed. If an ip
address is present the processor does nothing. If neither an
ip nor a domain is present a tag "unrecognized_domain" is added
to the event. Furthermore the domain label extraction processor
can now be configured with a tld suffix list.
=> Improve the domain label extraction processor

doc/source/user_manual/configuration/processor.rst, doc/source/user_manual/introduction.rst, logprep/processor/domain_label_extractor/processor.py, tests/testdata/unit/domain_label_extractor/rules/domain_label_extractor.json, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py
The previous tags only included one error tag when no domain was
recognized. With this commit tags will also be added when an IP
address was found in the target field. Now the added tags also
include the target field name such that it is possible to
distinguish between different fields and tags.
=> Add more informative domain label extractor tags

logprep/processor/list_comparison/processor.py, logprep/processor/list_comparison/rule.py
The list comparison processor did not make use of the performance of
sets or dictionaries as it was still iterating over every element.
This new implementation uses a slightly different datastructure to
speed up the matching of elements and lists. It now only iterates
over the number of lists given in a rule instead of each element
of all lists. This significantly speeds up the worst case scenario.
=> Improve list comparison performance

logprep/processor/list_comparison/factory.py, logprep/processor/list_comparison/processor.py, logprep/processor/list_comparison/rule.py, logprep/processor/normalizer/processor.py, logprep/processor/pseudonymizer/processor.py, tests/testdata/unit/list_comparison/rules/generic/user_check.json, tests/testdata/unit/list_comparison/rules/specific/user_check_specific.json, tests/unit/processor/base.py, tests/unit/processor/list_comparison/test_list_comparison.py, tests/unit/processor/list_comparison/test_list_comparison_rule.py
Refactor to use base class for list comparison tests. Part of a refactoring for all processors to use generic and specific rules.
=> refactor list comparison tests to use base class

logprep/util/schema_and_rule_checker.py, tests/unit/util/test_schema_and_rule_checker.py
Remove no longer existing labeler exceptions from schema validator
* The schema validation for the labeler should no longer cause import errors.
=> Remove no longer existing labeler exceptions from schema validator

logprep/processor/generic_adder/processor.py
The tree_config path was given as a positional argument resulting
in being interpreted as a Node instead of the proper config path
=> Fix init of the generic adder rule trees

logprep/processor/datetime_extractor/factory.py, logprep/processor/domain_label_extractor/factory.py, logprep/processor/labeler/factory.py, tests/unit/processor/domain_label_extractor/test_domain_label_extractor_factory.py
The processors datetime extractor, domain label extractor and
labeler weren't using the check_common_configuration method.
This is aligned in this pull request.
=> Refactor processor factories to use config check

.github/workflows/ci.yml, .github/workflows/main.yml, README.md, requirements.in, requirements.txt, requirements_dev.txt, tox.ini
Adjusts python requirements to allow for higher versions,
while still maintaining support for python 3.6. 
With that update also the tox environments such that the tests
can be run against all python versions. And also update the
github actions in order to continuously test logprep against the 
different versions.
=> Add python 3.7 to 3.9 support

doc/source/user_manual/configuration/logprep.rst, logprep/framework/pipeline.py, logprep/framework/pipeline_manager.py, logprep/run_logprep.py, logprep/runner.py, logprep/util/processor_stats.py, logprep/util/prometheus_exporter.py, tests/unit/framework/test_pipeline.py, tests/unit/framework/test_pipeline_manager.py, tests/unit/util/test_processor_stats.py, tests/unit/util/test_prometheus_exporter.py
To improve the visualizations in grafana a few changes have been
made. First and foremost stale metric database files will be removed
now when a pipeline fails. Furthermore, the metrics are prefixed
with 'logprep_' and the label is now called 'component'.
Additionally, the status logger is not stored in a list anymore
but in a namedtuple, which makes the unwrapping easier. Last but
not least a small fix in the documentation was done, variables
renamed and some linting issues fixed.
=> Refactor Prometheus Metrics

logprep/processor/processor_factory.py, logprep/processor/processor_factory_error.py, logprep/run_logprep.py, logprep/util/configuration.py, tests/unit/util/test_configuration.py
For issues #96 and #97. Makes logprep print out feedback on configuration errors even if it is executed via pex. Collects multiple errors before printing them.
=> Add config error handling for pex and collection of exceptions

.github/workflows/publish-release-to-pypi.yml
According to the [github action release ](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release) documentation the github ref already has the tag of the release. Adjusted the pipeline such that the github ref is used directly. Includes also a debug statement just in case, if successful then I will remove the statement in an additional pull-request.
=> Add debug statement for github action

.github/workflows/publish-release-to-pypi.yml
Also remove debug information as the github.ref
really does have the correct tag of the published
release.
=> remove wrong if condition in github action

.github/workflows/publish-release-to-pypi.yml, README.md, doc/source/installation.rst
With these changes applied logprep will be automatically 
distributed to the official pypi servers. The documentation
changes consider the new install and run procedures.
=> Change release destination to official pypi server

setup.py
To simplify the installation via `pip install logprep` only the abstract 
requirements should be given. That way pip can itself look, what 
versions suit best to the system of the installing client.
=> Use abstract dependencies for distribution

CHANGELOG.md, logprep/processor/generic_adder/processor.py, tests/unit/processor/generic_adder/test_generic_adder.py
Not initializing "_db_table" in the processor of the generic adder has led to some unexpected crashes if the SQL adder was disabled, but rules that utilize SQL where processed.
It was changed so that it's initialized with "None" again and it was changed to be an instance variable.
Furthermore, some unit tests that prevent this issue from happening again where added.
See #138.
=> Fix crash from not initialized class variable in sql adder

CHANGELOG.md, logprep/framework/pipeline.py, logprep/metrics/metric_exposer.py, logprep/metrics/metric_targets.py, tests/unit/metrics/test_metric_exposer.py, tests/unit/metrics/test_metric_targets.py
The call to store metrics was executed for every processed event.
It is only needed to be executed when the time to expose the metrics
has passed and only if the processes should be aggregated. If metrics
can be exposed independently then the shared dict is not used.
=> Fix metric tracking performance

.gitignore, CHANGELOG.md, doc/source/user_manual/configuration/connector.rst, logprep/connector/confluent_kafka.py, logprep/framework/pipeline.py, logprep/framework/pipeline_manager.py, logprep/util/configuration.py, tests/acceptance/test_full_message_pass_with_hmac.py, tests/acceptance/util.py, tests/unit/connector/test_confluent_kafka.py, tests/unit/framework/test_pipeline.py, tests/unit/util/test_configuration.py
This enables the pipeline to automatically add version information
to all events independent of the pipeline configuration.
This pull request also refactors the initialization of pipeline and 
multiprocessing pipeline objects. Furthermore it introduces a 
`preprocessing` config field to the connector consumer options. 
The already existing hmac options were moved under this new 
field while maintaining backwards capabilities. Meaning the hmac
can now be configured in two places. The old place under the
field `consumer` will lead to a deprecation warning, indicating a 
removal in the next major release. 
In an additional pull request the hmac implementation should also
move away from the connector and into the pipeline such that it is
an connector independent feature.
=> Add logprep and configuration version to event

CHANGELOG.md, logprep/processor/selective_extractor/processor.py, tests/unit/processor/selective_extractor/test_selective_extractor.py
The internal extracted list wasn't cleared between each event,
leading to duplication in the output of the processor. Now the
events are cleared such that only the result of the current event is
returned.
=> Fix selective extractor output

logprep/framework/pipeline.py, tests/unit/framework/test_pipeline.py
The logprep configuration was overwritten by the config of the
multiprocessing Process. This python class BaseProcess also contains
an attribute that's called '_config'. This resulted in a naming
conflict. Renaming the logprep config to _logprep_config fixed this
issue.
=> Fix pipeline config attribute name

CHANGELOG.md, logprep/connector/confluent_kafka.py, logprep/framework/pipeline.py, tests/acceptance/test_preprocessors.py
The unit tests for the preprocessor which adds version information to
an event didn't cover the config validation. This pull-requests adds
acceptances tests to test a full message pass with the preprocessor
activated and fixes a config validation error.
=> Fix preprocessor config validation

CHANGELOG.md, doc/source/user_manual/rule_language.rst, logprep/processor/normalizer/processor.py, logprep/processor/normalizer/rule.py, tests/unit/processor/normalizer/test_normalizer.py
In case no grok pattern of a rule matches it is now possible to
automatically add a grok failure fields which will contain the grok
target field as well as the first 100 characters of the pattern that
should have been matched.
This pull-request does also some refactoring and lint fixes.
=> Allow normalizer to write grok_failure fields

logprep/processor/normalizer/rule.py
Remove print statements that were accidentally left in a the normalizer.
=> Remove accidental print statements from normalizer

logprep/abc/processor.py, logprep/framework/pipeline.py, logprep/run_logprep.py
Fix pickling error in debug, but also remove some lazy logging, since the aggregator aggregates the strings ("... %s ...") before they get replaced with variables if it's being used.
=> Fix picklingerror in debug

logprep/util/time_measurement.py, tests/unit/connector/base.py
The `TimeMeasurement.measure_time` decorator was initially designed for processing times of the processors, but was recently also used for the input connectors. If the time measurement was enabled and was configured to append the result to the event it resulted in an error as the input connector method `get_next` does not receive an event as an argument, instead it receives a timeout argument. 
This fix introduces a check if the given argument is a dictionary or not.
Alternative solution would be to check if the `caller` is of type `Input`.
closes #189
=> Fix time measurement for get_next input connector

logprep/connector/elasticsearch/output.py, logprep/connector/opensearch/output.py, tests/unit/connector/test_opensearch_output.py
this fixes a keyerror if the document has a special _op_type field, which we are using to write to data_streams.
the key for the error info will become `create` instead of `index` if you are using a field `"op_type": "create"` in your document
=> fix keyerror for message with setted _op_type field

logprep/connector/elasticsearch/output.py, logprep/connector/opensearch/output.py
This clarifies the use of the cert in a better way to avoid, that someone has to look for it in the ssl lib.
Additionally, it is described how to handle with datastreams.
=> change documentation and config key for opensearch and elasticsearch

logprep/framework/rule_tree/rule_tree.py, tests/unit/framework/rule_tree/test_rule_tree.py, tests/unit/processor/selective_extractor/test_selective_extractor.py
The fix of the issue #166 and the corresponding pull request #168 introduced some non-deterministic behavior. Duplicate rules were filtered out by using a python `set` instead of a `list`, which in return resulted in the fact that the rules could be applied in different orders with each retrieval of matching rules. 
This pull requests uses a `list` again and removes duplicates manually by maintaining the original rule order. Also, to ensure this deterministic behavior in the future a new test was added.
=> Fix non-deterministic behavior

logprep/util/helper.py
This is a reimplementation of the `get_dotted_field_value` based on python builtin `functools.reduce` function.
It is much faster and I guess  it scales in O(n) if the depth increases.
The original time complexity was O(n*n).
This was my testcode for performance measurement:
```python
from logprep.util.helper import get_dotted_field_value, _retrieve_field_value_and_delete_field_if_configured
from time import perf_counter
testdict = {"key1": {"key2": {"key3": {"key4": {"key5": {"key6": "value"}}}}}}
start = perf_counter()
for _ in range(1_000_000):
get_dotted_field_value(testdict, "key1.key2.key3")
print(perf_counter() - start)
testdict = {"key1": {"key2": {"key3": {"key4": {"key5": {"key6": "value"}}}}}}
start = perf_counter()
for _ in range(1_000_000):
get_dotted_field_value(testdict, …
```
=> reimplement get_dotted_field_value

logprep/framework/pipeline.py, tests/acceptance/test_preprocessing.py, tests/acceptance/util.py, tests/unit/connector/base.py, tests/unit/framework/test_pipeline.py
The preprocessor that adds the version information didn't really add the corresponding information. It only added always emtpy strings. This pull request fixes this and revises the tests.
=> Fix add version info preprocessor and revice tests

logprep/processor/generic_adder/rule.py, logprep/processor/pre_detector/rule.py, tests/unit/processor/generic_adder/test_generic_adder_rule.py, tests/unit/processor/pre_detector/test_pre_detector_rule.py
The rule configuration validation has become to strict for some cases.
This pull requests aims to restore functionality in the generic adder and the pre detector that was lost due to this.
- In the pre detector an optional field `link` will be validated and and only added if it is not `None`.
- in the generic adder, added fields can have the type bool.
=> Adapt rule configuration validation

logprep/util/helper.py, tests/unit/util/test_helper_add_field.py
reimplement `add_field_to` with a slightly better performance but increased readability.
Testcode for performance measurement:
```python
from time import perf_counter
def original_add_field_to(event, output_field, content, extends_lists=False, overwrite_output_field=False):
assert not (
extends_lists & overwrite_output_field
), "An output field can't be overwritten and extended at the same time"
conflicting_fields = []
keys = output_field.split(".")
for idx, key in enumerate(keys):
if key not in event:
if idx == len(keys) - 1:
event[key] = content
break
event[key] = {}
if isinstance(event[key], dict) and idx < len(keys) - 1:
event = event[key]
elif (
isinstance(event[key], list)
and extends_lists
and idx == len(keys) - 1
and not overwrite_output_field
):
if isinstance(content, str): …
```
=> refactor add_field_to

logprep/registry.py, tests/unit/connector/test_elasticsearch_output.py
Typo: "elasticsearch" was "eleasticsearch"
=> Fix typo in elasticsearch output connector

CHANGELOG.md, logprep/framework/pipeline.py, logprep/metrics/metric.py, logprep/run_logprep.py, logprep/runner.py, tests/acceptance/util.py, tests/unit/metrics/test_metrics.py
Attributes that were of type `Metric` weren't reset properly. This fixes it and revises the initialization of the metric targets (moved from `run_logprep.py` to `pipeline.py`).
=> Fix reset of metric

logprep/processor/dropper/processor.py, tests/unit/processor/dropper/test_dropper.py
this reimplements the dropper with helper methods.
performance wise it has a slightly better performance on my machine.
performance testing code:
```python
from logging import DEBUG
from logprep.factory import Factory
from logprep.registry import Registry
from logprep.abc import Processor
from logprep.processor.dropper.rule import DropperRule
from time import perf_counter
from logging import getLogger
class OldDropper(Processor):
"""Normalize log events by copying specific values to standardized fields."""
rule_class = DropperRule
def _traverse_dict_and_delete(self, dict_: dict, sub_fields, drop_full: bool):
sub_field = sub_fields[0] if sub_fields else None
remaining_sub_fields = sub_fields[1:]
if not remaining_sub_fields and sub_field in dict_.keys():
del dict_[sub_field]
if ( …
```
=> reimplement dropper

CHANGELOG.md, README.md, logprep/processor/geoip_enricher/processor.py, logprep/processor/geoip_enricher/rule.py, tests/unit/processor/geoip_enricher/test_geoip_enricher.py
Extends the `geoip_enricher` such that it's output subfields can be customized via a rule configuration. Furthermore, some refactorings were done.
=> Geoip Enricher: Add config to customize target subfields

CHANGELOG.md, doc/source/development/coding_examples.rst, doc/source/development/notebooks/processor_examples/timestamp_differ.ipynb, doc/source/user_manual/configuration/processor.rst, doc/source/user_manual/configuration/rules.rst, logprep/abc/processor.py, logprep/processor/calculator/processor.py, logprep/processor/calculator/rule.py, logprep/processor/timestamp_differ/processor.py, logprep/processor/timestamp_differ/rule.py, logprep/registry.py, tests/testdata/unit/timestamp_differ/generic_rules/timestamp_differ_rule.json, tests/testdata/unit/timestamp_differ/specific_rules/timestamp_differ_rule.json, tests/unit/processor/timestamp_differ/test_timestamp_differ.py, tests/unit/processor/timestamp_differ/test_timestamp_differ_rule.py
This pull requests adds a new `timestamp_differ` processor which can calculate the time delta between two timestamps. The respective timestamp format can be specified each.
=> Add timestamp_differ processor

CHANGELOG.md, doc/source/user_manual/configuration/processor.rst, doc/source/user_manual/configuration/rules.rst, logprep/processor/calculator/processor.py, logprep/processor/calculator/rule.py, logprep/processor/field_manager/rule.py, logprep/processor/requester/processor.py, logprep/processor/requester/rule.py, logprep/processor/timestamp_differ/processor.py, logprep/processor/timestamp_differ/rule.py, logprep/registry.py, logprep/util/helper.py, requirements.in, requirements.txt, requirements_dev.in, requirements_dev.txt, tests/testdata/unit/requester/generic_rules/requester.json, tests/testdata/unit/requester/specific_rules/requester.json, tests/unit/processor/requester/test_requester.py, tests/unit/processor/requester/test_requester_rule.py
A processor to invoke http requests. Could be usefull to enrich events from an external api or
to trigger external systems by and with event field values.
Parses the response to enrich event data.
=> Add requester processor

CHANGELOG.md, logprep/processor/list_comparison/processor.py, logprep/processor/list_comparison/rule.py, tests/unit/processor/domain_resolver/test_domain_resolver.py, tests/unit/processor/list_comparison/test_list_comparison.py
* adds the feature to list_comparison processor to submit a template like `"http://${LOGPREP_TEST_TARGET}/${LOGPREP_LIST_SEARCH_BASE_PATH}/${LOGPREP_LIST}?ref=bla"` in `list_search_base_path` config option
=> add option to submit a template through `list_search_base_path`

logprep/processor/domain_label_extractor/processor.py, logprep/processor/domain_resolver/processor.py, logprep/processor/geoip_enricher/processor.py, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py, tests/unit/processor/domain_resolver/test_domain_resolver.py, tests/unit/processor/geoip_enricher/test_geoip_enricher.py
This PR fixes a bug, that the domain_label_extractor and domain_resolver download the tldlists during processing time. 
With this fix the tld lists were downloaded during setup time.
Additionally the lists were saved per process and per processor instance to avoid problems with getting a file lock on the downloaded artifacts.
=> fix artifacts load during process time

logprep/filter/expression/filter_expression.py, tests/unit/filter/test_filter_expression.py
The problem was, that the normalization did cut of everything after "$". However, having multiple "$" is valid even if redundant. This is a problem if an expected closing parenthesis is located after a "$".
Additionally, escaped "$" are handled now.
=> Fix error with regex normalization

logprep/run_logprep.py
The deprecation warnings weren't displayed in the console, so I activated them here by default.
=> Set deprecation filter to always

logprep/processor/list_comparison/processor.py, logprep/processor/pseudonymizer/processor.py, logprep/util/auto_rule_tester.py, tests/unit/processor/list_comparison/test_list_comparison.py, tests/unit/processor/pseudonymizer/test_pseudonymizer.py, tests/unit/util/test_auto_rule_tester.py
The auto-rule-tester didn't load the tldextract lists properly because the processor setup method wasn't called in the auto-rule-tester. This pull requests fixes it by calling all setup methods and adjusting the list_comparision processor as well as the pseudonymizer to make proper use of the setup method.
=> Fix auto rule tester to call all processor setup methods

CHANGELOG.md, doc/source/getting_started.rst, logprep/framework/pipeline.py, tests/unit/framework/test_pipeline.py
This pull requests evaluates the possibility to run the logprep pipeline without any connectors directly from python. That way logprep could be integrated into other libraries without having the need to deal with input/output connectors.
Following is a minimal example how it could be used:
```python
from logprep.framework.pipeline import Pipeline
config = {
"pipeline": [
{
"predetector": {
"type": "pre_detector",
"specific_rules": [
"tests/testdata/unit/pre_detector/rules/specific"
],
"generic_rules": [
"tests/testdata/unit/pre_detector/rules/generic"
],
"pre_detector_topic": "foo"
}
}
]
}
event = {
"winlog": {
"event_id": 123,
"event_data": {
"ServiceName": "VERY BAD"
}
}
}
print(event)
pipeline = Pipeline(config=config)
extra_outputs = pipeline.process_event(event)
print(event) …
```
=> Enable pipeline run without connectors

.github/workflows/ci.yml, CHANGELOG.md, doc/source/user_manual/configuration/configurationdata.rst, logprep/abc/getter.py, logprep/connector/elasticsearch/output.py, logprep/connector/opensearch/output.py, logprep/framework/pipeline.py, tests/unit/connector/test_elasticsearch_output.py, tests/unit/connector/test_opensearch_output.py, tests/unit/framework/test_pipeline.py, tests/unit/util/test_getter.py
* adds blacklist variable names to enrichment from environment, because we use a special variable LOGPREP_LIST in list_comparison
* fixes docker build for branch and not for main for PRs
* adds connection check for opensearch and elasticsearch output connectors
=> fix opensearch-output-connector-raises-to-late-if-unauthenticated 

logprep/framework/pipeline_manager.py, logprep/run_logprep.py, tests/unit/test_run_logprep.py
the configuration is verified already here:
https://github.com/fkie-cad/Logprep/blob/49303b87ee622502f90a9a220f0d3f52653317ac/logprep/runner.py#L133-L157
on reload the configuration is verified again here to prevent faulty config from loading:
https://github.com/fkie-cad/Logprep/blob/49303b87ee622502f90a9a220f0d3f52653317ac/logprep/runner.py#L236-L256
I think there is no need for this configuration verification in the pipeline manager. this will improve logprep start times
additionally the config was checked on logprep start in `run_logprep` so the config was checked 3 times for one start and in every verification the whole pipeline was instantiated and all rules were loaded.
=> remove verification of configuration in pipeline manager and run_logprep

logprep/processor/base/rule.py, logprep/processor/processor_strategy.py, tests/unit/processor/test_processor_strategy.py
The processor strategy applied rules in a random order due to using `set` at the wrong locations. This pull request moves the `set` operation to where it is really needed.
=> fix non-deterministic behavior and add test

logprep/framework/pipeline.py, logprep/util/aggregating_logger.py, logprep/util/auto_rule_tester/auto_rule_corpus_tester.py, logprep/util/configuration.py, logprep/util/rule_dry_runner.py, tests/acceptance/util.py, tests/unit/util/test_configuration.py, tests/unit/util/test_rule_dry_runner.py
- change dry_runner to use the logprep pipeline instead of the patched_runner
- move patched_runner code to test util.py (can be deleted once the old acceptance tests are revised)
- allow config validation without processor outputs
closes #350 #340
=> Fix dry_runner to deal with multiple outputs

logprep/abc/processor.py, logprep/processor/processor_strategy.py, tests/unit/processor/test_processor_strategy.py
Applying rules multiple times requires to match the rules at least 2 times.
Once for the 1. match and once to check if another match is necessary.
This can reduce the performance of Logprep significantly.
Therefore, this feature is made optional with this pull-request.
It is disabled per default and can be enabled on a processor basis by setting `apply_rules_multiple_times` to true.
=> Make multiple applications of rules by the same processor optional

logprep/framework/rule_tree/rule_parser.py, logprep/processor/calculator/rule.py, logprep/processor/dissector/rule.py, logprep/processor/domain_label_extractor/rule.py, logprep/processor/domain_resolver/rule.py, logprep/processor/dropper/rule.py, logprep/processor/field_manager/rule.py, logprep/processor/list_comparison/rule.py, logprep/processor/normalizer/processor.py, logprep/processor/pseudonymizer/processor.py, logprep/processor/pseudonymizer/rule.py, logprep/processor/requester/rule.py, logprep/processor/selective_extractor/rule.py, logprep/processor/template_replacer/processor.py, logprep/processor/timestamp_differ/rule.py, logprep/util/helper.py
this is a PR to improve logprep performance. the main idea behind this is, that splitting of string is an expensive operation and we could cache this easy. @ppcad could you please double check if this is really an improvement in performance. my local setup says it does.
=> avoid string splitting during processing

CHANGELOG.md, logprep/util/auto_rule_tester/auto_rule_corpus_tester.py, tests/unit/util/test_auto_rule_corpus_tester.py
Until now the tester used the caches of previous runs which led to changing results depending on which test data combination was executed. This pull request fixes the auto rule corpus tester cache handling by resetting all processors between test runs. Sadly this makes the auto rule corpus tester slower again as every test case has to setup all processors again.
=> Fix rule corpus tester processor caches

CHANGELOG.md, logprep/framework/pipeline.py, logprep/processor/normalizer/processor.py, logprep/util/helper.py, tests/acceptance/test_http_input.py
Baseline of main:
```
2.1283082099980675                                                                                                                                                                                            
2.162810495996382
2.1795665249956073
```
this PR:
```
1.560745990005671                                                                                                                                                                                    
1.5640459910064237
1.5819058579945704
```
testcode:
```python
from timeit import timeit
setup_code = """
import logging
logging.disable(logging.CRITICAL)
import json
from pathlib import Path
from logprep.framework.pipeline import Pipeline
from logprep.util.configuration import Configuration
input_data = …
```
=> improve pipeline performance

CHANGELOG.md, logprep/processor/geoip_enricher/processor.py, logprep/processor/geoip_enricher/rule.py, tests/unit/processor/geoip_enricher/test_geoip_enricher.py
Remove all geoip fields that are `None` from the geoip results, so that the results for different events always have the same data types. This was missing for the geoip enricher coordinates.
=> Remove all geoip enricher fields if they are None

logprep/processor/calculator/rule.py, logprep/processor/datetime_extractor/rule.py, logprep/processor/deleter/rule.py, logprep/processor/dissector/rule.py, logprep/processor/selective_extractor/rule.py, logprep/processor/timestamp_differ/rule.py
* mark inherited but not used fields in rules with `init=False, repr=False, eq=False` to signal, that they do not need to be rendered in external UI tools.
=> mark not used fields with init=False, repr=False, eq=False

CHANGELOG.md, MANIFEST.in, setup.py
The MANIFEST.in didn't include the grok pattern, such that logprep, if installed through pypi, didn't include the grok patterns.
I did test this through the [pypi test server](https://test.pypi.org/project/logprep/6.1.0.dev0/#files). It can be verified by running the following command in a new venv:
```bash
pip install --no-deps -i https://test.pypi.org/simple/ logprep==6.1.0.dev1
```
Afterwards you can check the installed site-packages of the venv. There you should find the logprep install with the grok patterns.
=> Fix packaging of logprep to include grok default pattern

CHANGELOG.md, logprep/processor/grokker/processor.py, logprep/processor/grokker/rule.py, logprep/util/grok/grok.py, tests/unit/processor/grokker/test_grok.py, tests/unit/processor/grokker/test_grokker.py, tests/unit/processor/grokker/test_grokker_rule.py
Previously it was not possible to use a list of grok pattern that try to write into the same output fields. This was because the list of grok pattern was merged to one large regex-pattern with the `|` operator. This pull request changes this behavior by considering each list element as a separate regex pattern. That way it is possible to write a grokker rule with multiple grok-pattern that all try to write to the same output field.
=> Allow same target names in grokker mapping list

CHANGELOG.md, logprep/processor/field_manager/processor.py, tests/unit/processor/field_manager/test_field_manager.py
Fix error handling of FieldManager if no mapped source field exists in the event.
=> fix error handling of fieldmanager if no mapped source field exists

CHANGELOG.md, logprep/processor/datetime_extractor/processor.py, logprep/processor/normalizer/processor.py, logprep/processor/pre_detector/ip_alerter.py, logprep/processor/timestamper/processor.py, logprep/util/rule_dry_runner.py, logprep/util/time.py, requirements.in, requirements.txt, requirements_dev.txt, tests/unit/processor/datetime_extractor/test_datetime_extractor.py, tests/unit/processor/normalizer/test_normalizer.py
replace with python native functions wrapped in `time.py` the requirement of `python-dateutil` still remains as it is used by other dependencies.
Due to this change some test had to be adjusted as every timestamp that does not have a timezone associated with it is considered to be a `UTC` timestamp instead of the timestamp of the local system. 
Closes #378
=> remove direct python-dateutil dependency

CHANGELOG.md, doc/source/user_manual/configuration/metrics.rst, logprep/metrics/metric_targets.py, logprep/processor/domain_label_extractor/processor.py, logprep/processor/domain_resolver/processor.py, logprep/processor/geoip_enricher/processor.py, logprep/util/prometheus_exporter.py, tests/unit/metrics/test_metric_targets.py, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py, tests/unit/processor/domain_resolver/test_domain_resolver.py, tests/unit/processor/geoip_enricher/test_geoip_enricher.py, tests/unit/util/test_prometheus_exporter.py
=> rework logprep temp files

CHANGELOG.md, logprep/filter/expression/filter_expression.py, logprep/framework/rule_tree/rule_parser.py, tests/unit/exceptions/processor/test_processing_warning.py, tests/unit/filter/test_filter_expression.py
- fields shouldn't be wrapped in quotes
- lucene regex query in opensearch doesn't return results with `^` and `$`
=> fix lucene filter representation

CHANGELOG.md, logprep/util/grok/patterns/ecs-v1/grok-patterns, logprep/util/grok_pattern_loader.py, tests/unit/util/test_grok_pattern.py, tests/unit/util/test_grok_pattern_loader.py
The previous regex pattern wasn't supported in python.
closes #413
=> fix UNIXPATH grok pattern

CHANGELOG.md, logprep/framework/pipeline.py, logprep/processor/domain_label_extractor/processor.py, logprep/processor/domain_resolver/processor.py, logprep/processor/geoip_enricher/processor.py, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py, tests/unit/processor/domain_resolver/test_domain_resolver.py, tests/unit/processor/geoip_enricher/test_geoip_enricher.py
The call `list_path.touch()` which initially creates the temporary file could be overwritten in the next processors `setup` call with empty content. A check if the file exists already prevents this.
=> prevent overwriting existing file

logprep/util/time.py, tests/unit/processor/normalizer/test_normalizer.py, tests/unit/processor/timestamper/test_timestamper.py, tests/unit/util/test_time.py
Make the timestamper and normalizer timestamp normalization yield results like before the TimeParser was added.
- The source timezone will be replaced and not converted in the TimeParser. Conversion happens in the normalizer/timestamper. Before this change, the absence of a timezone implied UTC, which does not have to be the case (except for UNIX timestamp). Instead the source_timezone is assumed.
- The TimeParser sets the current year instead of 1900 if no year was present in the timestamp, since it is far more likely that a missing year should be the current year instead of 1900.
=> Change timestamp conversion

CHANGELOG.md, logprep/processor/grokker/processor.py, logprep/processor/grokker/rule.py, logprep/util/grok/grok.py, tests/unit/processor/grokker/test_grokker.py
The `Grokker` implementation uses an updated set of Grok-Pattern compared the `Normalizer`. Some of these pattern are more complex which can lead to some edge cases where the underlying regex becomes quite complex as well, leading to a long run-time for matching strings. To handle these cases a timeout of one second will be added here. If the timeout is reached a `ProcessingError` is raised, as the normalization is not possible anymore.
To test the effect of the different pattern following code can be used. Switch the `new_pattern` and `old_pattern` in the `mock.patch` statements at the end to see different results. Furthermore, the `DOCUMENT` itself has an effect on the performance as well. The given example can lead to a processing time of 20 to 60 seconds, for the grokker and the …
=> Handle long-running grok pattern by introducing a timeout

CHANGELOG.md, logprep/abc/input.py, logprep/abc/processor.py, logprep/connector/confluent_kafka/input.py, logprep/framework/pipeline.py, logprep/processor/base/exceptions.py, tests/unit/connector/test_confluent_kafka_input.py, tests/unit/framework/test_pipeline.py
closes #424 
furthermore, `ProcessingCriticalError` aren't wrapped again inside `ProcessingCriticalError` and `events` are only cleared after they were written to the error output.
=> fix crash on invalid json input in kafka input connector

CHANGELOG.md, logprep/framework/pipeline.py, tests/unit/framework/test_pipeline.py
=> revise processing counter

CHANGELOG.md, logprep/util/time_measurement.py, tests/unit/util/test_time_measurement.py
Fix writing time measurements into the event after the deleter has deleted the event. The bug only
happened when the `metrics.measure_time.append_to_event` configuration was set to `true`.
=> Fix time_measurement for empty events after deleter deleted the event

logprep/util/helper.py
this could possible fix the memory leak experienced by you @ppcad
=> fix memory leak

.github/workflows/publish-release-to-pypi.yml
Change pypi publishing method to trusted publishers. Also splits the build and publishing into two jobs and sets inter-job dependencies. 
Publishing to `test.pypi.org` did work as can be seen here: https://test.pypi.org/project/logprep/
=> Update publish-release-to-pypi.yml to use trusted publishing 

CHANGELOG.md, logprep/filter/expression/filter_expression.py, logprep/framework/rule_tree/rule_parser.py, tests/unit/filter/test_lucene_filter.py, tests/unit/framework/rule_tree/test_rule_parser.py
=> always expect exists filter

.github/workflows/publish-release-to-pypi.yml
as quoted here in usage the `ref` key is not needed. perhaps we are on the wrong commit somehow
https://github.com/actions/checkout
=> fix release pipeline

CHANGELOG.md, logprep/framework/pipeline.py, tests/unit/framework/test_pipeline.py
This PR fixes an error in the `_handle_pipeline_error()` function that leads to `FatalOutputError` when `CriticalInputError` exceptions are handled.
=> Fix handling of `CriticalInputError` exceptions

CHANGELOG.md, logprep/connector/elasticsearch/output.py, logprep/connector/s3/output.py, tests/unit/connector/test_elasticsearch_output.py, tests/unit/connector/test_opensearch_output.py, tests/unit/connector/test_s3_output.py
Make `store_custom` in s3, opensearch and elasticsearch connector not call `batch_finished_callback` to prevent data loss that could be caused by partially processed events.
=> Set no offsets on store custom

logprep/connector/confluent_kafka/input.py, logprep/framework/pipeline_manager.py, tests/unit/connector/test_confluent_kafka_input.py
This PR fixes a serialization error caused by `KafkaError` objects that are embedded into `CriticalInputError` exceptions.
Closes #529.
=> Fix `FatalOutputError` caused by serializing `KafkaError`

quickstart/docker-compose.yml
This PR udpates the quickstart example to use FDA version 0.20.0.
=> Update FDA to version 0.21.0 in quickstart example

CHANGELOG.md, logprep/util/configuration.py, tests/unit/util/test_configuration.py, tests/unit/util/test_helper.py
This PR fixes the version generation for multiple configs.
the resulting configuration version is now concatenated in the same order as the configs were given.
=> fix merge of version string for multiple configs

CHANGELOG.md, logprep/connector/http/input.py, logprep/framework/pipeline.py, logprep/framework/pipeline_manager.py, quickstart/exampledata/config/http_pipeline.yml, tests/unit/connector/test_http_input.py, tests/unit/framework/test_pipeline_manager.py
this fixes an issue for not using multiprocessing on http_input connector:
to reproduce run on main:
* set logging to DEBUG in `quickstart/exampledata/config/http_pipeline.yml` 
```yaml
logger:
level: DEBUG
```
* then start logprep with `logprep run ./quickstart/exampledata/config/http_pipeline.yml`
* then start loadtest with `logprep generate http --input-dir ./quickstart/exampledata/input_logdata/ --target-url http://localhost:9000 --user "" --password "" --events 100000000 --batch-size 10000 --thread_count 2`
* the output shows, that only one process in storing output in kafka:
```
2024-04-17 15:00:32,608 Logprep Pipeline 1 DEBUG   : Stored output in kafka
2024-04-17 15:00:32,607 Logprep Pipeline 1 DEBUG   : Stored output in kafka
2024-04-17 15:00:32,608 Logprep Pipeline 1 DEBUG   : …
```
=> fix http connector only first process working

CHANGELOG.md, logprep/connector/http/input.py, logprep/framework/pipeline_manager.py, logprep/run_logprep.py
testing this is hard. too hard for me and so I decided to not add a tests for this.
test the fix explorative with:
```bash
logprep  run ./quickstart/exampledata/config/http_pipeline.yml
```
then press `CRTL + C`
you should get this:
```
^C2024-04-19 15:41:18,980 Logprep Runner INFO    : Shutting down
2024-04-19 15:41:18,980 Logprep Runner INFO    : Initiated shutdown
2024-04-19 15:41:18,980 Logprep Pipeline 2 DEBUG   : Stopping pipeline (MainProcess)
2024-04-19 15:41:18,980 Logprep Pipeline 2 DEBUG   : Stopping pipeline (MainProcess)
2024-04-19 15:41:20,659 Logprep Pipeline 1 DEBUG   : Stopping pipeline (MainProcess)
2024-04-19 15:41:20,659 Logprep Pipeline 1 DEBUG   : Stopping pipeline (MainProcess)
2024-04-19 15:41:25,673 Logprep HTTPServer INFO    : Shutting down
2024-04-19 …
```
=> fix broken gracefull shutdown

.gitignore, CHANGELOG.md, doc/source/conf.py, logprep/connector/http/input.py, logprep/util/credentials.py, pyproject.toml, quickstart/exampledata/config/credentials.yml, quickstart/exampledata/config/http_pipeline.yml, quickstart/exampledata/config/user_password.txt, tests/unit/connector/test_http_input.py, tests/unit/util/test_credentials.py, tests/unit/util/test_getter.py
This PR will add additional Basic Authentication functionality to the HTTP Connector:
- The Basic Auth Feature is completely modular in a Decorator and could be removed completely without dependencies to the endpoint code
- Basic Auth is configured using a additional `credentials.yaml` for example in the format below. The path to the file needs to be in the environment variable `LOGPREP_CREDENTIALS_FILE` beforehand running Logprep. The keys of the endpoints need to be matching to the http connector endpoints to apply basic auth:
```yaml
input:
endpoints:
/firstendpoint:
username: user
password_file: quickstart/exampledata/config/user_password.txt
/second*:
username: user
password: secret_password
```
- POST-Requests work as expected, when basic auth is configured
- To create proper …
=> Add Basic Auth to HTTP Connector

CHANGELOG.md, logprep/processor/grokker/rule.py, tests/unit/processor/grokker/test_grokker.py
=> Fix grokker rules that have fields with common prefixes

CHANGELOG.md, logprep/connector/http/input.py, logprep/metrics/exporter.py, logprep/util/configuration.py, logprep/util/http.py, quickstart/exampledata/config/http_pipeline.yml, tests/acceptance/test_full_configuration.py, tests/unit/connector/test_http_input.py, tests/unit/metrics/test_exporter.py, tests/unit/util/test_configuration.py
this change adds the uvicorn webserver to the metrics endpoint to be able to disable server side headers, and to enable an access log. Beside this, you are now able to configure ssl transport security for the metrics endpoint. 
closes #575
=> export metrics via uvicorn asgi app

CHANGELOG.md, quickstart/docker-compose.yml
* fixes logprep quickstart profile
* test with:
```bash
docker compose -f ./quickstart/docker-compose.yml --profile logprep up -d --build
docker logs logprep -f
```
=> fix logprep quickstart profile

CHANGELOG.md, logprep/abc/component.py, logprep/connector/confluent_kafka/input.py, logprep/connector/confluent_kafka/output.py, logprep/connector/dummy/output.py, logprep/connector/file/input.py, logprep/processor/list_comparison/processor.py, logprep/util/configuration.py, tests/acceptance/test_full_configuration.py, tests/unit/component/base.py, tests/unit/connector/test_confluent_kafka_input.py, tests/unit/connector/test_dummy_output.py, tests/unit/connector/test_elasticsearch_output.py, tests/unit/connector/test_jsonl_output.py, tests/unit/connector/test_opensearch_output.py, tests/unit/connector/test_s3_output.py, tests/unit/processor/list_comparison/test_list_comparison.py, tests/unit/util/test_auto_rule_tester.py, tests/unit/util/test_configuration.py
it turns out, that the bug should be handled for all missing files during verification of Configuration.
closes #597 
TODO:
=> add calling setup during configuration verify

quickstart/docker-compose.yml
* docker networking depends on environment
* you cant't predict that `172.17.0.1` is always the network docker uses
* configured fixed ip subnets for all networks and fixed the host entry for prometheus.
=> fix quickstart compose setup for WSL

.github/workflows/ci.yml, .github/workflows/main.yml, .github/workflows/publish-latest-dev-release-to-pypi.yml, .github/workflows/publish-release-to-pypi.yml, .github/workflows/testing.yml, CHANGELOG.md, pyproject.toml
includes following changes:
- update CHANGELOG.md to include python version limitation
- build containers for 3.12.3
- split test workflow (unit,acceptance)
- increase wait time for http_input acceptance test and split test workflow (unit,acceptance)
These changes were done because of #612
=> set upper python version limit to <3.12.4 and revise github workflows

CHANGELOG.md, logprep/processor/pseudonymizer/processor.py, tests/unit/processor/pseudonymizer/test_pseudonymizer.py
check with:
1. create `pipeline.yml`
```yaml
input:
dummy:
type: dummy_input
documents: [{ "foo": "bar" }]
output:
dummy:
type: dummy_output
pipeline:
- pseudonymizername:
type: pseudonymizer
specific_rules:
- filter: foo
pseudonymizer:
mapping:
foo: DOES_NOT_EXIST
generic_rules: []
outputs:
- dummy: pseudonyms_topic
pubkey_analyst: analyst.crt
pubkey_depseudo: depseudo.crt
hash_salt: secret_salt
regex_mapping: tests/testdata/unit/pseudonymizer/pseudonymizer_regex_mapping.yml
max_cached_pseudonyms: 1000000
```
2. create needed pseudo keys
```bash
logprep pseudo generate -f analyst 1024
logprep pseudo generate -f depseudo 2048
```
run logprep with:
```bash
logprep run ./pipeline.yml
```
you will get nice error output complaining the regex mapping is not found
=> Pseudonymizer late error on non existing regexmapping

charts/logprep/Chart.yaml, charts/logprep/templates/deployment.yaml, charts/logprep/values.yaml, pyproject.toml, tests/unit/charts/test_deployment.py
updates the chart to support extra environment and extra secrets. please see values documentation for more.
will be released by merge in main with given version.
=> extend helm chart with extra environment and extra secrets

CHANGELOG.md, logprep/connector/http/output.py
according to https://docs.python-requests.org/en/latest/user/advanced/#timeouts timeout parameter can be specified as tupe for read and write timeouts
=> Fix http output timeout

logprep/connector/confluent_kafka/input.py, tests/unit/connector/test_confluent_kafka_input.py
Prevent pipeline crash if kafka input tries to decode non-unicode character.
=> Handle UnicodeDecodeError in kafka input

CHANGELOG.md, logprep/abc/component.py, logprep/connector/confluent_kafka/input.py, logprep/connector/confluent_kafka/output.py, logprep/factory.py, logprep/processor/amides/processor.py, logprep/processor/domain_label_extractor/processor.py, logprep/processor/domain_resolver/processor.py, logprep/processor/geoip_enricher/processor.py, tests/acceptance/test_amides.py, tests/unit/component/base.py, tests/unit/connector/test_confluent_kafka_common.py, tests/unit/connector/test_confluent_kafka_input.py, tests/unit/connector/test_confluent_kafka_output.py, tests/unit/connector/test_dummy_input.py, tests/unit/connector/test_jsonl_output.py, tests/unit/connector/test_opensearch_output.py, tests/unit/connector/test_s3_output.py, tests/unit/processor/amides/test_amides.py, tests/unit/processor/domain_label_extractor/test_domain_label_extractor.py, tests/unit/processor/domain_resolver/test_domain_resolver.py, tests/unit/processor/geoip_enricher/test_geoip_enricher.py, tests/unit/processor/grokker/test_grokker.py, tests/unit/processor/pseudonymizer/test_pseudonymizer.py, tests/unit/util/test_configuration.py
=> make configuration immutable

.github/workflows/ci.yml, .github/workflows/publish-latest-dev-release-to-pypi.yml, .github/workflows/publish-release-to-pypi.yml, .github/workflows/testing.yml, .gitignore, CHANGELOG.md, Cargo.toml, Dockerfile, MANIFEST.in, logprep/framework/pipeline_manager.py, pyproject.toml, rust/.gitignore, rust/lib.rs, rust/tests/mod.rs, tests/unit/framework/test_pipeline.py, tests/unit/framework/test_pipeline_manager.py, tests/unit/rust/test_rust.py
this adds rust toolchain with setuptools-rust and multiplatform builds with cibuildwheel.
see changelog for more.
ToDo:
=> add rust toolchain

.github/workflows/publish-latest-dev-release-to-pypi.yml, .github/workflows/publish-release-to-pypi.yml, CHANGELOG.md, tests/unit/util/test_configuration.py
This suggests to disable arm64 builds for now because it blocks the release pipeline.
=> Fix release pipeline broken for arm images

Dockerfile, pyproject.toml
- Remove wheel runtime dependency. It is only needed at build time.
- Dont install pip into venv. It is not needed at runtime. Fixes CVE-2023-5752.
- Remove setuptools dependency after building. Fixes CVE-2022-40897. Note that setuptools is only a build depdendency, but is still present at runtime, because the geoip2 package references a vulnerable version as a dependency.
Scanned using `trivy image IMAGE --ignore-unfixed`
```
Python (python-pkg)
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 2, CRITICAL: 0)
┌───────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬──────────────────────────────────────────────────────────┐
│        Library        │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │ …
```
=> Remove unneeded dependencies

CHANGELOG.md, logprep/connector/confluent_kafka/input.py, tests/unit/connector/test_confluent_kafka_input.py
This removes the reassign behavior addressed in #673 and the buggy manual commit feature addressed in #653
closes #673 
closes #653
=> Remove broken kafka implementations

Dockerfile, logprep/util/grok/grok.py
https://github.com/fkie-cad/Logprep/pull/682 introduced a regression, where the logprep binary is not available in the final image. This is because it is installed with the system-wide pip, which installs the binary to`/opt/bitnami/python/bin/` instead of `/opt/venv/bin/`. pip was removed from the venv, because it is unneeded at runtime. The `logprep --version` check, which ensures that logprep is properly installed still passed, because `/opt/bitnami/python/bin/` is also in `PATH`. To avoid such issues in the future, I changed the command to explicitly use `/opt/venv/bin/logprep`.
To install logprep into the venv, it is required to install pip into the virtual environment and use the pip version from the venv instead of the system-wide installation from bitnami. Therefore the …
=> Fix docker image and avoid implicit setuptools runtime dependency

CHANGELOG.md, charts/logprep/Chart.yaml, charts/logprep/templates/deployment.yaml, charts/logprep/values.yaml
this adds the possibility to set the  terminationGracePeriodSeconds in helm chart values. this is needed to ensure by time to drain all queues and message backlogs and close the connections on shutdown (pod deletion)
default is set to 300 seconds which means that the kubernetes scheduler will wait at maximum 300 seconds after sending SIGTERM before sending a SIGKILL signal.
=> make `terminationGracePeriodSeconds` configurable.

.github/workflows/ci.yml, .github/workflows/publish-latest-dev-release-to-pypi.yml, .github/workflows/publish-release-to-pypi.yml, .github/workflows/testing.yml, .trivyignore, Dockerfile, trivy.yaml
This PR sets up container image scanning using Trivy from Aquasecurity.
- Images will be scanned in the CI workflow.
- Scanning is performed in the containerbuild job after pushing the image to the registry.
- Scan results are available in the workflow log (the comment from github-advanced-security originated from a test to store SARIF outputs in the GitHub security tab and can be ignored).
- When an unfixed critical CVE is found, the pipeline exits with status code 1. Images are already pushed to the registry at this point and can be pulled for further debugging.
- fail-fast was disabled, so that if one containerbuild job from the matrix fails, the other jobs are still executed.
This PR also changes the Python base image version back from 3.12.3 to 3.12. It was pinned to version 3.12.3, …
=> Scan images using Trivy

CHANGELOG.md, logprep/processor/generic_adder/mysql_connector.py, pyproject.toml
Update import for new mysql-connector-python version and unpin the version.
The mysql connector will be eventually removed, but this is required now, since trivy finds a vulnerability in the old version, which was pinned before this pull request.
=> 629 no support for the mysql connector python library in version 900

logprep/util/time.py, tests/unit/util/test_time.py
The solution adjusts the timestamp to the actual length so that the timestamp is processed correctly regardless of its precision (milliseconds, microseconds, nanoseconds). It dynamically takes into account how many additional digits are present and scales accordingly to obtain a correct time representation in seconds.Tests are also added. fixed issue 687
=> add dynamic scaling of time representations

CHANGELOG.md, logprep/connector/confluent_kafka/input.py, tests/unit/connector/test_confluent_kafka_input.py
- Prevent store_offsets from being called before the first message is pulled.
- Add unit test to ensure store_offsets is not called incorrectly.
=> fix store_offsets call when last_valid_record is None

CHANGELOG.md, logprep/processor/pseudonymizer/processor.py, tests/unit/processor/pseudonymizer/test_pseudonymizer.py
=> fix pseudonymizer cache metrics

tests/unit/connector/test_confluent_kafka_output.py
you can check with:
```bash
pytest ./tests/unit/connector/test_confluent_kafka_output.py -vv --durations=10 --durations-min=1.0
```
main:
this branch:
=> speed up kafka output tests

CHANGELOG.md, logprep/processor/requester/rule.py, tests/unit/processor/requester/test_requester_rule.py
=> fix requester documentation

logprep/connector/confluent_kafka/input.py, logprep/connector/confluent_kafka/output.py, tests/unit/connector/test_confluent_kafka_input.py, tests/unit/connector/test_confluent_kafka_output.py
The SSL config was missing in the kafka admin client, which led to errors and failed health checks if SSL was used.
=> Add missing SSL config to kafka admin clients

CHANGELOG.md, logprep/connector/opensearch/output.py, tests/unit/connector/test_opensearch_output.py
=> add shut_down method to opensearch output connector

CHANGELOG.md, logprep/metrics/metrics.py, tests/unit/metrics/test_metrics.py
Considering that the feature `LOGPREP_APPEND_MEASUREMENT_TO_EVENT ` will be removed in the future I decided to just recreate the previous behavior. Before #696 was merged it was ignored if the value was already present or not. I ensured here now that the same behavior is happing again, by using `_add_field_to_silent_fail`. It is to note though that this means, that only the first processor/rule of a kind will write it's processing times into the event. Consecutive processors/rules of the same type will then be ignored. 
closes #721
=> Fix FieldsExist warning using `LOGPREP_APPEND_MEASUREMENT_TO_EVENT `

README.md, doc/source/conf.py, doc/source/configuration/rules.rst, logprep/abc/processor.py, logprep/framework/rule_tree/rule_tree.py, pyproject.toml, tests/unit/framework/rule_tree/test_rule_tree.py, tests/unit/processor/base.py, tests/unit/processor/clusterer/test_clusterer.py, tests/unit/processor/labeler/test_labeler.py
- Extracted RuleTree configuration into a dedicated `Config` class for improved modularity.
- Updated unit tests and references to reflect the refactoring changes in RuleTree initialization.
- Add documentation to rst docs
=> Add rule tree configuration validation

.pre-commit-config.yaml
- id: check-toml -> loads pyproject.toml to check syntax
- id: debug-statements -> looks for orphaned `breakpoint()` in files
- id: no-commit-to-branch -> disables commit to "main" 
- bump versions to latest used black an isort versions
=> revise pre-commit config

.github/workflows/ci.yml, .pre-commit-config.yaml, CHANGELOG.md, logprep/connector/http/input.py, logprep/util/rstr/__init__.py, logprep/util/rstr/rstr_base.py, logprep/util/rstr/xeger.py, pyproject.toml
this removes `rstr` dependency by assimilate code from here: https://github.com/leapfrogonline/rstr
this library was used to generate random GET requests for health checks based on the regex of an `http_endpoint` in `http_input` connector
=> remove `rstr` dependency

.github/workflows/ci.yml, .pre-commit-config.yaml, .vscode/extensions.json, logprep/abc/input.py, logprep/abc/processor.py, logprep/connector/file/input.py, logprep/connector/opensearch/output.py, logprep/generator/http/input.py, logprep/processor/calculator/rule.py, logprep/processor/generic_resolver/rule.py, logprep/processor/labeler/processor.py, logprep/processor/pre_detector/rule.py, logprep/processor/pseudonymizer/processor.py, logprep/processor/requester/rule.py, logprep/processor/timestamper/rule.py, logprep/util/configuration.py, logprep/util/processor_generator.py, pyproject.toml, tests/unit/connector/test_file_input_default_config.py
* added mypy type checks to CI
* removed linting of test files from CI
* fixed typing in some example files
=> add `mypy` type checker

CHANGELOG.md, logprep/abc/connector.py, logprep/abc/input.py, logprep/connector/http/input.py, logprep/util/helper.py, tests/unit/connector/base.py, tests/unit/connector/test_http_input.py
This PR schould make it possible for logprep to add a whole event as a string to a designated target field.
=> add ability to write the full event to one singular target field

CHANGELOG.md, logprep/connector/confluent_kafka/input.py, logprep/connector/confluent_kafka/output.py, tests/unit/connector/test_confluent_kafka_common.py, tests/unit/connector/test_confluent_kafka_input.py
In the confluent Kafka input connector, logging inside ```_revoke_callback`` can crash due the consumer being closed or in an invalid state.
=> fix revoke callback error handling

tests/unit/test_run_logprep.py
remove of testing invoking auto rule tests because it freezes the testrunner.
=> remove auto-rule-cli-tests

CHANGELOG.md, logprep/util/time.py, tests/unit/util/test_time.py
`TimeParser.now()` created a timestamp with the local timezone and then changed the timezone to UTC if no timezone was specified.
With this pull request a UTC timestamp will be created instead.
Example:
* Let's say the local timezone is `+02:00` and no timezone was provided to `TimeParser.now()`
* `TimeParser` would create a timestamp `2025-01-01T02:00:00.000` in local time, but without a timezone
* The timezone would be set to UTC without adapting the time values, resulting in `2025-01-01T02:00:00.000+00:00`
* However, `2025-01-01T00:00:00.000+00:00` would be correct
=> Fix timezone for getting current time via TimeParser

logprep/util/tag_yaml_loader.py, tests/unit/util/test_tag_yaml_loader.py
Custom YAML anchor tags did not work with large files if the anchors were set near the end of a file, because it relied on a buffer that could change.
This fixes it by no longer relying on a buffer to track changes and load tag values.
Mainly `_extract_anchor_value` and `clear_anchors_if_buffer_changed ` (now `clear_anchors_if_stream_changed`) where changed.
`_extract_anchor_value` parses the node value instead of using the read buffer.
`clear_anchors_if_stream_changed` now checks if the current line number of the yaml reader is smaller than the last one, which would mean that a new stream/file has been opened. Furthermore, checks are now performed by an implicit tag that is processed for every node.
=> Make custom yaml tag loader work with large files

.gitignore, logprep/ng/abc/event.py, logprep/ng/event/error_event.py, logprep/ng/event/event_state.py, logprep/ng/event/log_event.py, tests/unit/ng/event/test_error_event.py, tests/unit/ng/event/test_event.py, tests/unit/ng/event/test_event_state.py, tests/unit/ng/event/test_filtered_event.py, tests/unit/ng/event/test_log_event.py, tests/unit/ng/event/test_pseudonym_event.py, tests/unit/ng/event/test_sre_event.py
changes state type in `Event.__init__` to EventStateType to make creating Events with custom state more intuitive
add `__repr__` method to event state reflecting the current state
=> change eventstate handling
